version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - "443:443"
      - "80:80"
      - "5222:22"
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local'    
        gitlab_rails['gitlab_shell_ssh_port'] = 5222
        gitlab_rails['time_zone'] = 'Europe/Berlin'
        gitlab_rails['gitlab_email_from'] = 'gitlab-no-reply@local'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab Administrator'
        gitlab_rails['gitlab_email_reply_to'] = 'admin@hlocal.com'
        gitlab_rails['backup_keep_time'] = 14515200
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.local.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "no-reply@local.com"
        gitlab_rails['smtp_password'] = "changeMeToSomethingGood"
        gitlab_rails['smtp_domain'] = "local.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
        logging['logrotate_frequency'] = "weekly"
        logging['logrotate_rotate'] = 52
        logging['logrotate_compress'] = "compress"
        logging['logrotate_method'] = "copytruncate"
        logging['logrotate_delaycompress'] = "delaycompress"
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
        nginx['ssl_protocols'] = "TLSv1.2"
        nginx['logrotate_frequency'] = "weekly"
        nginx['logrotate_rotate'] = 52
        nginx['logrotate_compress'] = "compress"
        nginx['logrotate_method'] = "copytruncate"
        nginx['logrotate_delaycompress'] = "delaycompress"

    volumes:
      - /etc/localtime:/etc/localtime:ro      
      - ./volume-data/config:/etc/gitlab
      - ./volume-data/logs:/var/log/gitlab
      - ./volume-data/data:/var/opt/gitlab
 
    networks:
      dev-net:
        aliases:
          - gitlab.dev.internal.example.com
networks:
  dev-net:
    external:
      name: development